version: "3.8"

services:
  todo-list:
    extends:
      file: go-todo-list/docker-compose.yaml
      service: todo-list
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    extends:
      file: frontend/docker-compose.yaml
      service: frontend
    networks:
      - app-network
    depends_on:
      - keycloak
      - todo-list

  db:
    extends:
      file: infra/db/docker-compose.yaml
      service: db
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    extends:
      file: infra/sso/docker-compose.yaml
      service: keycloak
    networks:
      - app-network
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - db
  pgadmin:
    extends:
      file: infra/db/docker-compose.yaml
      service: pgadmin
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    external: true

volumes:
  postgres_data:
    external: true
  keycloak_data:
    external: true
