services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: shared-db
      KC_DB_URL_DATABASE: shared_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: yourpassword
      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_PROXY: edge
      KC_HOSTNAME: "http://localhost:8080/keycloak"
    command: start-dev

networks:
  app-network:
    external: true

volumes:
  keycloak_data:
