version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: shared-db
      DB_DATABASE: shared_db
      DB_USER: postgres
      DB_PASSWORD: yourpassword
    command: start-dev
    networks:
      - app-network
    volumes:
      - keycloak_data:/opt/keycloak/data

networks:
  app-network:
    external: true

volumes:
  keycloak_data:
