services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: shared-db
      KC_DB_URL_DATABASE: shared_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: yourpassword
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost # Change to sarkis.dev for production
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY_HEADERS: forwarded

      # Additional production settings
      # KC_HEALTH_ENABLED: "true"
      # KC_METRICS_ENABLED: "true"
      # KC_LOG_LEVEL: INFO  # Add for production
    command: start-dev # Change to 'start' for production

networks:
  app-network:
    external: true

volumes:
  keycloak_data:
