version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:80" # Change before going to prod
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
      #- ./.htpasswd:/etc/nginx/.htpasswd:Z # Optional safe layer
    networks:
      - app-network
    depends_on:
      - frontend
      - todo-list
      - keycloak
    restart: unless-stopped

networks:
  app-network:
    external: true
